!:PUNC:Chunking
":PUNC:Non_Chunking
%:PUNC:Non_Chunking
':PUNC:Non_Chunking
(:PUNC:Non_Chunking
):PUNC:Non_Chunking
***:PUNC:Non_Chunking
**:PUNC:Non_Chunking
*:PUNC:Non_Chunking
+:PUNC:Non_Chunking
,:PUNC:Chunking
-:PUNC:Non_Chunking
.:PUNC:Chunking
...:PUNC:Non_Chunking
/:PUNC:Non_Chunking
::PUNC:Chunking
;:PUNC:Chunking
<:PUNC:Non_Chunking
=:PUNC:Non_Chunking
>:PUNC:Non_Chunking
?:PUNC:Non_Chunking
@:PUNC:Non_Chunking
[:PUNC:Non_Chunking
]:PUNC:Non_Chunking
_:PUNC:Non_Chunking
`:PUNC:Non_Chunking
aby:C:Sub_C
a:C:Cor_CONJ
ačkoli:C:Sub_C
ale:C:Cor_CONJ
anebo:C:Cor_CONJ
ani:C:Cor_CONJ
aniž:C:Sub_C
ať:C:Sub_C
avšak:C:Cor_CONJ
až:C:Sub_C
během:P
bez:P
blízko:P
čtrnácti:Q:Num_CARD
čtrnáct:Q:Num_CARD
čtyrech:Q:Card_NUM
čtyřech:Q:Card_NUM
čtyrem:Q:Card_NUM
čtyřem:Q:Card_NUM
čtyřiceti:Q:Num_CARD
čtyřicet:Q:Num_CARD
čtyřicíti:Q:Num_CARD
čtyři:Q:Card_NUM
čtyrma:Q:Card_NUM
čtyřma:Q:Card_NUM
čtyrmi:Q:Card_NUM
čtyřmi:Q:Card_NUM
čtyr:Q:Card_NUM
čtyř:Q:Card_NUM
čtyry:Q:Card_NUM
daleko od:P
deseti:Q:Num_CARD
deset:Q:Num_CARD
desíti:Q:Num_CARD
devadesáti:Q:Num_CARD
devadesát:Q:Num_CARD
devatenácti:Q:Num_CARD
devatenáct:Q:Num_CARD
devět:Q:Num_CARD
devíti:Q:Num_CARD
díky:P
díky:P
dokud:C:Sub_C
dvaceti:Q:Num_CARD
dvacet:Q:Num_CARD
dvacíti:Q:Num_CARD
dvanácti:Q:Num_CARD
dvanáct:Q:Num_CARD
dva:Q:Card_NUM
dvěma:Q:Card_NUM
dvěmi:Q:Card_NUM
dvě:Q:Card_NUM
dvou:Q:Card_NUM
ho:O:Pers_PRON
i:C:Cor_CONJ
jak:C:Sub_C
jakmile:C:Sub_C
jako:C:Sub_C
já:O:Pers_PRON
jeden:Q:Card_NUM
jedna:Q:Card_NUM
jedněch:Q:Card_NUM
jedněma:Q:Card_NUM
jedněmi:Q:Card_NUM
jedněm:Q:Card_NUM
jedné:Q:Card_NUM
jedním:Q:Card_NUM
jedni:Q:Card_NUM
jednoho:Q:Card_NUM
jednom:Q:Card_NUM
jednomu:Q:Card_NUM
jedno:Q:Card_NUM
jednou:Q:Card_NUM
jednu:Q:Card_NUM
jedny:Q:Card_NUM
jeho:O:Pers_PRON
jej:O:Pers_PRON
jemu:O:Pers_PRON
jenomže:C:Sub_C
jenže:C:Sub_C
je:O:Pers_PRON
jestli:C:Sub_C
jestliže:C:Sub_C
jich:O:Pers_PRON
jimi:O:Pers_PRON
jim:O:Pers_PRON
jím:O:Pers_PRON
ji:O:Pers_PRON
jí:O:Pers_PRON
kdežto:C:Sub_C
kdyby:C:Sub_C
kdykoli:C:Sub_C
kdykoliv:C:Sub_C
když:C:Sub_C
ke:P
kolem:P
k:P
kromě:P
kvuli:P
kvůli:P
kvůli:P
mě:O:Pers_PRON
mezi:P
mezi:P
meztímco:C:Sub_C
mimo:P
mi:O:Pers_PRON
místo:P
mne:O:Pers_PRON
mně:O:Pers_PRON
mnou:O:Pers_PRON
mu:O:Pers_PRON
my:O:Pers_PRON
nad:P
námi:O:Pers_PRON
nám:O:Pers_PRON
na:P
naproti:P
na rozdíl od:P
nás:O:Pers_PRON
navzdor:P
navzdory:P
nebo:C:Cor_CONJ
neboť:C:Sub_C
nedaleko od:P
než:C:Sub_C
nich:O:Pers_PRON
nicméně:C:Sub_C
nimi:O:Pers_PRON
nim:O:Pers_PRON
ním:O:Pers_PRON
ni:O:Pers_PRON
ní:O:Pers_PRON
ob:P
okolo:P
ona:O:Pers_PRON
oni:O:Pers_PRON
on:O:Pers_PRON
ony:O:Pers_PRON
o:P
osmdesáti:Q:Num_CARD
osmdesát:Q:Num_CARD
osmi:Q:Card_NUM
osmnácti:Q:Num_CARD
osmnáct:Q:Num_CARD
osm:Q:Card_NUM
padesáti:Q:Num_CARD
padesát:Q:Num_CARD
patnácti:Q:Num_CARD
patnáct:Q:Num_CARD
podél:P
pod:P
pokud:C:Sub_C
pomocí:P
po:P
před:P
před:P
přes:P
přestože:C:Sub_C
přim:P
pro:P
pro:P
proti:P
proti:P
proto:C:Cor_CONJ
protože:C:Sub_C
šedesáti:Q:Num_CARD
šedesát:Q:Num_CARD
sedmdesáti:Q:Num_CARD
sedmdesát:Q:Num_CARD
sedmi:Q:Card_NUM
sedmnácti:Q:Num_CARD
sedmnáct:Q:Num_CARD
sedm:Q:Card_NUM
se:P
šesti:Q:Num_CARD
šestnácti:Q:Num_CARD
šestnáct:Q:Num_CARD
šest:Q:Num_CARD
set:Q:Num_CARD
s:P
stech:Q:Num_CARD
stě:Q:Num_CARD
sto:Q:Num_CARD
stům:Q:Num_CARD
sty:Q:Num_CARD
takže:C:Sub_C
tebe:O:Pers_PRON
tebou:O:Pers_PRON
tě:O:Pers_PRON
ti:O:Pers_PRON
tisíc:Q:Num_CARD
tobě:O:Pers_PRON
třebaže:C:Sub_C
třech:Q:Card_NUM
třema:Q:Card_NUM
třemi:Q:Card_NUM
třem:Q:Card_NUM
třiceti:Q:Num_CARD
třicet:Q:Num_CARD
třicíti:Q:Num_CARD
třinácti:Q:Num_CARD
třináct:Q:Num_CARD
tři:Q:Card_NUM
tří:Q:Card_NUM
ty:O:Pers_PRON
u:P
uprostřed:P
vámi:O:Pers_PRON
vám:O:Pers_PRON
vás:O:Pers_PRON
vedle:P
ve:P
v:P
vůči:P
vy:O:Pers_PRON
za:P
zatímco:C:Sub_C
zato:C:Sub_C
že:C:Sub_C
ze:P
z:P
